using System.Xml.Serialization;

namespace TsePublicV2;

// This class was generated by (paste special)
// NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.
/// <remarks/>
[System.SerializableAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1", IsNullable = false)]
public partial class diffgram
{

    private TradeLastDayTradeLastDay[] tradeLastDayField;

    [System.Xml.Serialization.XmlArrayAttribute(Namespace = "")]
    [XmlArrayItem("TseNSCStart", IsNullable = false)]
    public TseNSCStartTseNSCStart[] TseNSCStart { get; set; }


    [System.Xml.Serialization.XmlArrayAttribute(Namespace = "")]
    [XmlArrayItem("TradeSelectedDate", IsNullable = false)]
    public TradeSelectedDateTradeSelectedDate[] TradeSelectedDate { get; set; }
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Namespace = "")]
    [System.Xml.Serialization.XmlArrayItemAttribute("TradeLastDay", IsNullable = false)]
    public TradeLastDayTradeLastDay[] TradeLastDay
    {
        get
        {
            return this.tradeLastDayField;
        }
        set
        {
            this.tradeLastDayField = value;
        }
    }

}